// export const existingList = [
//     {
//         id : 'item_1',
//         name : 'Revivify Self Heal Lite 2 years',
//         stock_in_hand : 100,
//         country_price : 1000,
//         state_price : 1400,
//         city_price : 2800,
//         image : 'https://www.libertyautoworx.com/wp-content/uploads/2020/05/Revivify-Logo.png?x79941',
//         new_updated : 0,
//         history : [],
//         is_added_to_cart : false,
//         cart_quantity : 0,
//         created_date : new Date(),
//     },
//     {
//         id : 'item_2',
//         name : 'Revivify Self Heal Pro 3 years',
//         stock_in_hand : 100,
//         country_price : 1400,
//         state_price : 1800,
//         city_price : 2400,
//         image : 'https://www.libertyautoworx.com/wp-content/uploads/2020/05/Revivify-Logo.png?x79941',
//         new_updated : 0,
//         history : [],
//         is_added_to_cart : false,
//         cart_quantity : 0,
//         created_date : new Date(),
//     },
//     {
//         id : 'item_4',
//         name : 'Revivify Graphene Self Heal Lite 2 years',
//         stock_in_hand : 100,
//         country_price : 900,
//         state_price : 930,
//         city_price : 960,
//         image : 'https://www.libertyautoworx.com/wp-content/uploads/2020/05/Revivify-Logo.png?x79941',
//         new_updated : 0,
//         history : [],
//         is_added_to_cart : false,
//         cart_quantity : 0,
//         created_date : new Date(),
//     },
//     {
//         id : 'item_5',
//         name : 'Revivify Graphene Self Heal Pro 3 years',
//         stock_in_hand : 100,
//         country_price : 400,
//         state_price : 500,
//         city_price : 580,
//         image : 'https://www.libertyautoworx.com/wp-content/uploads/2020/05/Revivify-Logo.png?x79941',
//         new_updated : 0,
//         history : [],
//         is_added_to_cart : false,
//         cart_quantity : 0,
//         created_date : new Date(),
//     },
//     {
//         id : 'item_6',
//         name : 'Revivify Graphene Self Heal Ultra 5 years',
//         stock_in_hand : 100,
//         country_price : 490,
//         state_price : 510,
//         city_price : 528,
//         image : 'https://www.libertyautoworx.com/wp-content/uploads/2020/05/Revivify-Logo.png?x79941',
//         new_updated : 0,
//         history : [],
//         is_added_to_cart : false,
//         cart_quantity : 0,
//         created_date : new Date(),
//     },
// ]


// export const newList = [
//     {
//         id : 'item_2',
//         name : 'Revivify Self Heal Pro 3 years',
//         stock_in_hand : 100,
//         country_price : 1400,
//         state_price : 1800,
//         city_price : 2400,
//         image : 'https://www.libertyautoworx.com/wp-content/uploads/2020/05/Revivify-Logo.png?x79941',
//         new_updated : 0,
//         history : [],
//         is_added_to_cart : false,
//         cart_quantity : 0,
//         created_date : new Date(),
//     },
//     {
//         id : 'item_3',
//         name : 'Revivify Self Heal Ultra 5 years',
//         stock_in_hand : 40,
//         country_price : 3000,
//         state_price : 3140,
//         city_price : 3280,
//         image : 'https://www.libertyautoworx.com/wp-content/uploads/2020/05/Revivify-Logo.png?x79941',
//         new_updated : 0,
//         history : [],
//         is_added_to_cart : false,
//         cart_quantity : 0,
//         created_date : new Date(),
//     },
//     {
//         id : 'item_8',
//         name : 'Testing new ',
//         stock_in_hand : 100,
//         country_price : 900,
//         state_price : 930,
//         city_price : 960,
//         image : 'https://www.libertyautoworx.com/wp-content/uploads/2020/05/Revivify-Logo.png?x79941',
//         new_updated : 0,
//         history : [],
//         is_added_to_cart : false,
//         cart_quantity : 0,
//         created_date : new Date(),
//     },
// ]